import pptxgen from 'pptxgenjs'

const COLORS = {
    // Brand Colors
    primary: "10B981",      // Emerald
    secondary: "111827",    // Dark charcoal
    accent: "34D399",       // Light emerald

    // Backgrounds
    background: "F8FAFC",
    white: "FFFFFF",
    card: "FFFFFF",
    cardAlt: "F3F4F6",

    // Text
    text: "1F2937",
    heading: "111827",
    muted: "6B7280",

    // Borders
    border: "E5E7EB",

    // Footer
    footer: "9CA3AF"
};



export const generatePPT = async (data) => {
    const ppt = new pptxgen();

    ppt.layout = "LAYOUT_WIDE";
    ppt.title = data.title;
    ppt.subject = data.title;
    ppt.company = "Zentra AI";
    ppt.author = "Zentra AI";

    ppt.theme = {
        headFontFace: "Aptos Display",
        bodyFontFace: "Aptos",

    }

    ppt.defineLayout({
        name: "CUSTOM",
        width: 13.333,
        height: 7.5
    });

    addCover(ppt, data);

    data?.slides?.forEach((slide, i) => {
        addContentSlide(ppt, slide.title, slide.points, i + 1, data.slides.length);
    });


    addThankyou(ppt)
    return ppt;

}

const addCover = (ppt, data) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary
    };

    // Top Emerald Strip
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,

        fill: { color: COLORS.primary },
        line: { color: COLORS.primary }
    });

    // Right Accent Strip
    slide.addShape(ppt.ShapeType.rect, {
        x: 12.95,
        y: 0,
        w: 0.38,
        h: 7.5,

        fill: { color: COLORS.accent },
        line: { color: COLORS.accent }
    });

    slide.addText(data.title, {
        x: 0.8,
        y: 1.7,
        w: 11.7,
        h: 0.8,

        align: "center",
        bold: true,
        fontFace: "Aptos Display",
        fontSize: 30,

        color: "FFFFFF"
    });

    if (data.subtitle) {

        slide.addText(data.subtitle, {
            x: 1,
            y: 2.7,
            w: 11.5,

            align: "center",

            fontSize: 16,
            italic: true,

            color: "D1D5DB"
        });

    }

    slide.addText("Generated by Zentra AI", {
        x: 0,
        y: 6.95,
        w: 13.33,

        align: "center",

        fontSize: 10,
        color: "9CA3AF"
    });

};

const addContentSlide = (ppt, title, points, page, total) => {

    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.background
    };

    // Left Accent Bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 0.18,
        h: 7.5,

        fill: { color: COLORS.primary },
        line: { color: COLORS.primary }
    });

    slide.addText(title, {
        x: 0.7,
        y: 0.35,
        w: 12,

        fontFace: "Aptos Display",
        fontSize: 24,
        bold: true,

        color: COLORS.heading
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 0.7,
        y: 0.9,
        w: 12,

        line: {
            color: COLORS.border,
            width: 1
        }
    });

    const visiblePoints = points.slice(0, 6);

    visiblePoints.forEach((point, i) => {

        const y = 1.25 + i * 0.82;

        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.6,

            fill: {
                color: i % 2 ? COLORS.cardAlt : COLORS.card
            },

            line: {
                color: COLORS.border
            },

            radius: 0.08
        });

        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.95,
            y: y + 0.19,
            w: 0.14,
            h: 0.14,

            fill: {
                color: COLORS.primary
            },

            line: {
                color: COLORS.primary
            }
        });

        slide.addText(point, {
            x: 1.2,
            y: y + 0.07,

            w: 11,
            h: 0.35,

            fontSize: 15,
            color: COLORS.text,
            fit: "shrink"
        });

    });

    slide.addShape(ppt.ShapeType.line, {
        x: 0.7,
        y: 6.7,
        w: 12,

        line: {
            color: COLORS.border,
            width: 1
        }
    });

    slide.addText("Zentra AI", {
        x: 0.7,
        y: 6.82,

        fontSize: 10,
        color: COLORS.footer
    });

    slide.addText(`${page} / ${total}`, {
        x: 11.8,
        y: 6.82,

        w: 0.8,

        align: "right",

        fontSize: 10,
        color: COLORS.footer
    });

};


const addThankyou = (ppt) => {

    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary
    };

    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,

        fill: { color: COLORS.primary },
        line: { color: COLORS.primary }
    });

    slide.addText("Thank You!", {
        x: 0,
        y: 2.15,
        w: 13.33,

        align: "center",

        fontFace: "Aptos Display",
        fontSize: 34,
        bold: true,

        color: "FFFFFF"
    });

    slide.addText("Questions?", {
        x: 0,
        y: 3.05,
        w: 13.33,

        align: "center",

        fontSize: 18,
        color: "D1D5DB"
    });

    slide.addText("Generated by Zentra AI", {
        x: 0,
        y: 6.95,
        w: 13.33,

        align: "center",

        fontSize: 10,
        color: "9CA3AF"
    });

};
