import PDFDocument from 'pdfkit'
export const generatePDF = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "Zentra AI",
                Title: data.title,
                Creator: "Zentra AI"
            }
        });

        const chunks = [];

        doc.on("data", (chunk) => {
            chunks.push(chunk)
        });

        doc.on("end", () => resolve(Buffer.concat(chunks)));

        doc.on("error", () => reject);

        // Page settings
        doc.page.margins = {
            top: 60,
            bottom: 60,
            left: 60,
            right: 60,
        };

        // ======================
        // Title
        // ======================
        doc
            .font("Helvetica-Bold")
            .fontSize(28)
            .fillColor("#1F2937")
            .text(data.title, {
                align: "center",
            });

        if (data.subtitle) {
            doc.moveDown(0.6);

            doc
                .font("Helvetica")
                .fontSize(13)
                .fillColor("#6B7280")
                .text(data.subtitle, {
                    align: "center",
                });
        }

        // Space after title
        doc.moveDown(1.2);

        // Divider
        const pageWidth =
            doc.page.width -
            doc.page.margins.left -
            doc.page.margins.right;

        const y = doc.y;

        doc
            .strokeColor("#E5E7EB")
            .lineWidth(1)
            .moveTo(doc.page.margins.left, y)
            .lineTo(doc.page.margins.left + pageWidth, y)
            .stroke();

        doc.moveDown(1.5);

        // ======================
        // Sections
        // ======================
        data.sections.forEach((section) => {

            // Section Heading
            doc
                .font("Helvetica-Bold")
                .fontSize(18)
                .fillColor("#111827")
                .text(section.heading);

            doc.moveDown(0.6);

            // Bullet Points
            section.points.forEach((point) => {
                doc
                    .font("Helvetica")
                    .fontSize(12)
                    .fillColor("#374151")
                    .text(`•  ${point}`, {
                        indent: 12,
                        lineGap: 6,
                        paragraphGap: 4,
                        align: "left",
                    });
            });

            doc.moveDown(1.2);
        });

        // ======================
        // Footer Divider
        // ======================
        const footerY = doc.y;

        doc
            .strokeColor("#E5E7EB")
            .lineWidth(1)
            .moveTo(doc.page.margins.left, footerY)
            .lineTo(doc.page.width - doc.page.margins.right, footerY)
            .stroke();

        doc.moveDown(0.8);

        // ======================
        // Footer
        // ======================
        doc
            .font("Helvetica")
            .fontSize(10)
            .fillColor("#9CA3AF")
            .text("Generated by Zentra AI", {
                align: "center",
            });

        doc.end();

    })
}